// Generated by `yarn tokens:ios` in the SHARPIT web repository. Do not edit.
//
// The web design system is the single source of truth for design values (ADR-041).
// To change a color, edit `src/lib/brand/brand-tokens.ts` or `src/app/globals.css`
// in the SHARPIT repository and re-run the exporter.

import SwiftUI
import UIKit

/// A resolved sRGB color, exported from the web token set.
nonisolated struct SharpitRGBA: Equatable, Sendable {
    let red: Double
    let green: Double
    let blue: Double
    let alpha: Double
}

/// Semantic colors, light and dark, mirroring `:root` and `.dark` in `globals.css`.
///
/// `nonisolated`, and not by preference: UIKit calls a dynamic color's trait closure on
/// whichever thread resolves it, and SwiftUI resolves colors on its own renderer thread.
/// Under main-actor-by-default the closure — and the lazy init of every constant below —
/// would assert the main queue and trap there. Colors are pure values; they have no
/// business on an actor.
nonisolated enum SharpitColor {
    /// `--background`
    static let background = dynamic(
        light: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.0587, green: 0.1234, blue: 0.0399, alpha: 1.0000)
    )

    /// `--foreground`
    static let foreground = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000)
    )

    /// `--card`
    static let card = dynamic(
        light: SharpitRGBA(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1079, green: 0.1832, blue: 0.0866, alpha: 1.0000)
    )

    /// `--card-foreground`
    static let cardForeground = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000)
    )

    /// `--popover`
    static let popover = dynamic(
        light: SharpitRGBA(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1079, green: 0.1832, blue: 0.0866, alpha: 1.0000)
    )

    /// `--popover-foreground`
    static let popoverForeground = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000)
    )

    /// `--primary`
    static let primary = dynamic(
        light: SharpitRGBA(red: 0.1622, green: 0.4349, blue: 0.1385, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000)
    )

    /// `--primary-foreground`
    static let primaryForeground = dynamic(
        light: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1079, green: 0.1832, blue: 0.0866, alpha: 1.0000)
    )

    /// `--secondary`
    static let secondary = dynamic(
        light: SharpitRGBA(red: 0.9394, green: 0.9458, blue: 0.9107, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1522, green: 0.2213, blue: 0.1331, alpha: 1.0000)
    )

    /// `--secondary-foreground`
    static let secondaryForeground = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000)
    )

    /// `--muted`
    static let muted = dynamic(
        light: SharpitRGBA(red: 0.9394, green: 0.9458, blue: 0.9107, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1522, green: 0.2213, blue: 0.1331, alpha: 1.0000)
    )

    /// `--muted-foreground`
    static let mutedForeground = dynamic(
        light: SharpitRGBA(red: 0.3997, green: 0.3997, blue: 0.3997, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.6896, green: 0.7332, blue: 0.6889, alpha: 1.0000)
    )

    /// `--accent`
    static let accent = dynamic(
        light: SharpitRGBA(red: 0.9024, green: 0.9713, blue: 0.8166, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.2017, green: 0.2624, blue: 0.1380, alpha: 1.0000)
    )

    /// `--accent-foreground`
    static let accentForeground = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000)
    )

    /// `--highlight`
    static let highlight = dynamic(
        light: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000)
    )

    /// `--highlight-foreground`
    static let highlightForeground = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1079, green: 0.1832, blue: 0.0866, alpha: 1.0000)
    )

    /// `--ink-surface`
    static let inkSurface = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000)
    )

    /// `--ink-surface-foreground`
    static let inkSurfaceForeground = dynamic(
        light: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.0587, green: 0.1234, blue: 0.0399, alpha: 1.0000)
    )

    /// `--ink-accent`
    static let inkAccent = dynamic(
        light: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.0587, green: 0.1234, blue: 0.0399, alpha: 1.0000)
    )

    /// `--chip-surface`
    static let chipSurface = dynamic(
        light: SharpitRGBA(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1079, green: 0.1832, blue: 0.0866, alpha: 1.0000)
    )

    /// `--destructive`
    static let destructive = dynamic(
        light: SharpitRGBA(red: 0.8441, green: 0.2053, blue: 0.1915, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9008, green: 0.2649, blue: 0.2401, alpha: 1.0000)
    )

    /// `--border`
    static let border = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 0.1200),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 0.1200)
    )

    /// `--input`
    static let input = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 0.1400),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 0.1400)
    )

    /// `--ring`
    static let ring = dynamic(
        light: SharpitRGBA(red: 0.1622, green: 0.4349, blue: 0.1385, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000)
    )

    /// `--analysis-surface`
    static let analysisSurface = dynamic(
        light: SharpitRGBA(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1079, green: 0.1832, blue: 0.0866, alpha: 1.0000)
    )

    /// `--analysis-surface-alt`
    static let analysisSurfaceAlt = dynamic(
        light: SharpitRGBA(red: 0.9394, green: 0.9458, blue: 0.9107, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1270, green: 0.2032, blue: 0.1056, alpha: 1.0000)
    )

    /// `--analysis-border`
    static let analysisBorder = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 0.1600),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 0.1400)
    )

    /// `--analysis-grid`
    static let analysisGrid = dynamic(
        light: SharpitRGBA(red: 0.1110, green: 0.2277, blue: 0.0758, alpha: 0.0800),
        dark: SharpitRGBA(red: 0.9888, green: 0.9888, blue: 0.9679, alpha: 0.0800)
    )

    /// `--signal-recovery`
    static let signalRecovery = dynamic(
        light: SharpitRGBA(red: 0.3040, green: 0.5137, blue: 0.3366, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.5347, green: 0.7261, blue: 0.5586, alpha: 1.0000)
    )

    /// `--signal-base`
    static let signalBase = dynamic(
        light: SharpitRGBA(red: 0.1622, green: 0.4349, blue: 0.1385, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.8279, green: 0.9810, blue: 0.5998, alpha: 1.0000)
    )

    /// `--signal-tempo`
    static let signalTempo = dynamic(
        light: SharpitRGBA(red: 0.5998, green: 0.6885, blue: 0.3708, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.7255, green: 0.8109, blue: 0.5214, alpha: 1.0000)
    )

    /// `--signal-threshold`
    static let signalThreshold = dynamic(
        light: SharpitRGBA(red: 0.7628, green: 0.6655, blue: 0.2831, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.8561, green: 0.7669, blue: 0.4281, alpha: 1.0000)
    )

    /// `--signal-vo2`
    static let signalVo2 = dynamic(
        light: SharpitRGBA(red: 0.8399, green: 0.4593, blue: 0.1369, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9311, green: 0.5675, blue: 0.2976, alpha: 1.0000)
    )

    /// `--signal-neutral`
    static let signalNeutral = dynamic(
        light: SharpitRGBA(red: 0.3997, green: 0.3997, blue: 0.3997, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.6896, green: 0.7332, blue: 0.6889, alpha: 1.0000)
    )

    /// `--signal-caution`
    static let signalCaution = dynamic(
        light: SharpitRGBA(red: 0.6207, green: 0.3881, blue: 0.0000, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9973, green: 0.7648, blue: 0.2835, alpha: 1.0000)
    )

    /// `--signal-risk`
    static let signalRisk = dynamic(
        light: SharpitRGBA(red: 0.7314, green: 0.0410, blue: 0.0630, alpha: 1.0000),
        dark: SharpitRGBA(red: 1.0000, green: 0.4217, blue: 0.3661, alpha: 1.0000)
    )

    /// `--health-status-ok`
    static let healthStatusOk = dynamic(
        light: SharpitRGBA(red: 0.2975, green: 0.4610, blue: 0.2615, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.5512, green: 0.7260, blue: 0.5129, alpha: 1.0000)
    )

    /// `--health-status-watch`
    static let healthStatusWatch = dynamic(
        light: SharpitRGBA(red: 0.6207, green: 0.3881, blue: 0.0000, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9973, green: 0.7648, blue: 0.2835, alpha: 1.0000)
    )

    /// `--health-status-verify`
    static let healthStatusVerify = dynamic(
        light: SharpitRGBA(red: 0.3040, green: 0.5137, blue: 0.3366, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.5347, green: 0.7261, blue: 0.5586, alpha: 1.0000)
    )

    /// `--health-status-attention`
    static let healthStatusAttention = dynamic(
        light: SharpitRGBA(red: 0.7314, green: 0.0410, blue: 0.0630, alpha: 1.0000),
        dark: SharpitRGBA(red: 1.0000, green: 0.4217, blue: 0.3661, alpha: 1.0000)
    )

    /// `--record-accent`
    static let recordAccent = dynamic(
        light: SharpitRGBA(red: 0.8399, green: 0.4593, blue: 0.1369, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.9311, green: 0.5675, blue: 0.2976, alpha: 1.0000)
    )

    /// `--radial-track`
    static let radialTrack = dynamic(
        light: SharpitRGBA(red: 0.9394, green: 0.9458, blue: 0.9107, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.1522, green: 0.2213, blue: 0.1331, alpha: 1.0000)
    )

    /// `--radial-empty`
    static let radialEmpty = dynamic(
        light: SharpitRGBA(red: 0.7685, green: 0.7796, blue: 0.7685, alpha: 1.0000),
        dark: SharpitRGBA(red: 0.2472, green: 0.3288, blue: 0.2247, alpha: 1.0000)
    )

    static func dynamic(light: SharpitRGBA, dark: SharpitRGBA) -> Color {
        Color(uiColor: UIColor { traits in
            let token = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(
                red: token.red,
                green: token.green,
                blue: token.blue,
                alpha: token.alpha
            )
        })
    }
}

/// Sport identity, from `SPORT_IDENTITY_HEX` — one chromatic family per activity type.
/// Never Lime Pulse: the highlight stays brand punctuation for the product, not for a sport.
nonisolated enum SharpitSportColor {
    /// `SPORT_IDENTITY_HEX.RUN`
    static let run = SharpitRGBA(red: 0.9176, green: 0.3451, blue: 0.0471, alpha: 1.0000)

    /// `SPORT_IDENTITY_HEX.BIKE`
    static let bike = SharpitRGBA(red: 0.0196, green: 0.5882, blue: 0.4118, alpha: 1.0000)

    /// `SPORT_IDENTITY_HEX.SWIM`
    static let swim = SharpitRGBA(red: 0.0078, green: 0.5176, blue: 0.7804, alpha: 1.0000)

    /// `SPORT_IDENTITY_HEX.STRENGTH`
    static let strength = SharpitRGBA(red: 0.8824, green: 0.1137, blue: 0.2824, alpha: 1.0000)

    /// `SPORT_IDENTITY_HEX.TRIATHLON`
    static let triathlon = SharpitRGBA(red: 0.0510, green: 0.5804, blue: 0.5333, alpha: 1.0000)

    /// `SPORT_IDENTITY_HEX.HIKE`
    static let hike = SharpitRGBA(red: 0.7059, green: 0.3255, blue: 0.0353, alpha: 1.0000)

    /// `SPORT_IDENTITY_HEX.OTHER`
    static let other = SharpitRGBA(red: 0.1843, green: 0.4196, blue: 0.1569, alpha: 1.0000)

    static func color(_ token: SharpitRGBA) -> Color {
        Color(red: token.red, green: token.green, blue: token.blue, opacity: token.alpha)
    }
}

/// Non-color primitives exported from `brand-tokens.ts`.
nonisolated enum SharpitTokens {
    /// `BRAND.radius` — card and control radius.
    static let radius: CGFloat = 16.0000
}
